# Generated by Django 5.0 on 2023-12-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=20)),
                ('Registration', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=50)),
            ],
        ),
    ]
